info:
  description: This API specification provides endpoints for a fully-authenticated system, including features for user authentication, account management, and access to protected resources. It supports registration, login, password recovery, email verification, and secure access to user-specific data.
  title: Full-Auth API
  version: 1.0.0
openapi: 3.0.0
paths:
  /api/v1/auth/reset-password:
    post:
      summary: Reset Password
      description: Allows users to reset their password using a valid reset token. Requires the user's email, a new password, and the reset token to be included in the request body.
      requestBody:
        content:
          application/json:
            example:
              email: user@example.com
              password: new_password
              token: "sample_reset_token_here"
      responses:
        '200':
          description: Password reset successfully.
  /auth/forgot-password:
    post:
      summary: Forgot Password
      description: Initiates a password recovery process by sending a reset token to the specified email address.
      requestBody:
        content:
          application/json:
            example:
              email: user@example.com
      responses:
        '200':
          description: Password reset email sent successfully.
  /auth/login:
    post:
      summary: User Login
      description: Authenticates a user and returns a session or access token on successful login. Requires an email and password in the request body.
      requestBody:
        content:
          application/json:
            example:
              email: user@example.com
              password: user_password
      responses:
        '200':
          description: User logged in successfully.
  /auth/logout:
    delete:
      summary: User Logout
      description: Logs out the authenticated user, invalidating their session or token.
      responses:
        '200':
          description: User logged out successfully.
  /auth/me:
    get:
      summary: Show User Details
      description: Retrieves the authenticated user's details, such as name, email, and other profile information.
      responses:
        '200':
          description: User details retrieved successfully.
  /auth/register:
    post:
      summary: User Registration
      description: Allows a new user to register an account by providing their name, email, and password.
      requestBody:
        content:
          application/json:
            example:
              email: user@example.com
              name: John Doe
              password: secure_password
      responses:
        '200':
          description: User registered successfully.
  /auth/update:
    patch:
      summary: Update User Details
      description: Allows the authenticated user to update their profile details. Accepts partial updates.
      requestBody:
        content:
          application/json:
            example:
              name: Updated Name
      responses:
        '200':
          description: User details updated successfully.
  /auth/verify-email:
    get:
      summary: Verify Email
      description: Confirms the user's email address by validating a unique token sent to their email during registration.
      responses:
        '200':
          description: Email verified successfully.
  /dashboard:
    get:
      summary: Dashboard
      description: Retrieves dashboard data for the authenticated user. Contains user-specific metrics and details.
      responses:
        '200':
          description: Dashboard data retrieved successfully.
  /protected:
    get:
      summary: Protected Route
      description: Provides access to a protected route that requires user authentication. Only accessible to authorized users.
      responses:
        '200':
          description: Protected content retrieved successfully.
